version: '3'
services: 
  db: 
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
      PGDATA: /tmp
    volumes:
    - ./docker/pgdata:/var/lib/postgresql/data