version: '3'
services: 
  dart_week_api:
    build: 
      context: ./
      dockerfile:  ./docker/Dockerfile
    ports: 
      - 80:80
    links: 
      - db
    depends_on: 
      - db
    networks:
      default:
          external:
              name: my-net
  db: 
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    networks:
      default:
          external:
              name: my-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dart
      PGDATA: /tmp
    volumes:
    - ./docker/pgdata:/var/lib/postgresql/data